import { expect, test } from '@playwright/test';
import { readFileSync } from 'node:fs';

for (const width of [1440, 390]) {
  test(`construction contact and consent workflow at ${width}`, async ({ page, context }, info) => {
    await page.setViewportSize({ width, height: width === 390 ? 844 : 900 });
    const failures: string[] = [];
    page.on('pageerror', error => failures.push(error.message));
    await page.goto('/');
    await page.getByTestId('map').waitFor({ state: 'visible' });
    await page.locator('.parcel-row').first().click();
    await page.getByRole('button', { name: 'Start investigation', exact: true }).click();
    await page.getByLabel('Investigation name', { exact: true }).fill(`Construction access ${width}`);
    await page.getByLabel('Project name', { exact: true }).fill('Harbourside walkover');
    await page.getByLabel('Requesting company and contact').fill('Example Construction / Project Manager');
    await page.getByLabel('Reply address or email').fill('projects@example.com');
    await page.getByLabel('Retention review date').fill('2027-09-01');
    const sections = page.getByRole('navigation', { name: 'Case sections' });
    await sections.getByRole('button', { name: 'Titles', exact: true }).click();
    await page.getByRole('button', { name: 'Add title', exact: true }).click();
    await page.getByLabel('Title number', { exact: true }).fill('AV12345');
    await page.getByLabel('Title evidence reference', { exact: true }).fill('Current register and plan held in project DMS / test fixture');
    await page.getByLabel('Title evidence date', { exact: true }).fill('2026-09-01');
    await page.getByLabel('Parcel relationship').selectOption('part');
    await page.getByLabel('Extent assessment and plan reference').fill('Access strip hatched red on plan A');
    await page.getByLabel('Title assessment', { exact: true }).selectOption('checked');
    await page.getByLabel('Title checked by', { exact: true }).fill('Project land reviewer');
    await page.getByLabel('Title checked on', { exact: true }).fill('2026-09-02');
    await sections.getByRole('button', { name: 'Parties', exact: true }).click();
    await page.getByRole('button', { name: 'Add party', exact: true }).click();
    await page.getByLabel('Party name', { exact: true }).fill('Example Estates Ltd');
    await page.getByLabel('Related title').selectOption({ label: 'AV12345' });
    await page.getByLabel('Correspondence address').fill('Project correspondence address / fixture');
    await page.getByLabel('Contact email', { exact: true }).fill('land@example.com');
    await page.getByLabel('Contact source and permitted-use assessment').fill('Directly supplied by party for project correspondence; use approved by project team');
    await page.getByLabel('Contact checked on').fill('2026-09-02');
    await page.getByLabel('Commercial contact use').selectOption('approved');
    await page.getByLabel('Authority evidence reference').fill('Written delegation held in project DMS');
    await page.getByLabel('Authority checked by').fill('Project land reviewer');
    await page.getByLabel('Authority checked on').fill('2026-09-02');
    await sections.getByRole('button', { name: 'Requests', exact: true }).click();
    await page.getByRole('button', { name: 'Add consent request' }).click();
    await page.getByLabel('Proposed activities').fill('Walkover survey only. No excavation.');
    await page.getByLabel('Exact land scope and plan reference').fill('Access strip hatched red on plan A');
    await page.getByLabel('Valid from', { exact: true }).fill('2026-09-10');
    await page.getByLabel('Valid until', { exact: true }).fill('2026-09-20');
    await page.getByLabel('Conditions and restrictions').fill('Daylight only. Notify occupier before access.');
    await page.getByRole('button', { name: 'Save investigation', exact: true }).click();
    await expect(page.getByRole('status')).toContainText('Revision 0');
    const requestPromise = context.waitForEvent('page');
    await page.getByRole('button', { name: 'Request draft', exact: true }).click();
    const request = await requestPromise;
    await expect(request.locator('body')).toContainText('DRAFT / NOT SENT');
    await expect(request.locator('body')).toContainText('Walkover survey only. No excavation.');
    await expect(request.locator('body')).toContainText('Silence will not be treated as consent');
    await request.close();
    await expect(page.getByLabel('Consent decision')).toHaveValue('not requested');
    await page.getByLabel('Consent decision').selectOption('awaiting response');
    await page.getByLabel('Request sent on').fill('2026-09-03');
    await sections.getByRole('button', { name: 'Correspondence', exact: true }).click();
    await page.getByRole('button', { name: 'Add correspondence' }).click();
    await page.getByLabel('Correspondence date', { exact: true }).fill('2026-09-03');
    await page.getByLabel('Direction', { exact: true }).selectOption('outgoing');
    await page.getByLabel('Correspondence summary').fill('Request and plan A sent by project team outside the application.');
    await page.getByRole('button', { name: 'Save investigation', exact: true }).click();
    await expect(page.getByRole('status')).toContainText('Revision 1');
    await sections.getByRole('button', { name: 'Documents', exact: true }).click();
    await page.getByLabel('Evidence document', { exact: true }).setInputFiles({ name: 'permission.txt', mimeType: 'text/plain', buffer: Buffer.from('Consent response fixture. Walkover only; no excavation.') });
    await expect(page.getByRole('status')).toContainText('Document saved. Revision 2');
    const reference = await page.locator('.case-document code').innerText();
    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('link', { name: 'Download evidence' }).click();
    const download = await downloadPromise;
    expect(readFileSync((await download.path())!, 'utf8')).toContain('Consent response fixture');
    await sections.getByRole('button', { name: 'Requests', exact: true }).click();
    await page.getByLabel('Consent decision').selectOption('granted');
    await page.getByRole('button', { name: 'Save investigation', exact: true }).click();
    await expect(page.getByRole('alert')).toContainText('Decisions need');
    await page.getByLabel('Response received on').fill('2026-09-04');
    await page.getByLabel('Signatory name and capacity').fill('Example signatory / authorised agent');
    await page.getByLabel('Consent evidence reference', { exact: true }).fill(reference);
    await page.getByRole('button', { name: 'Save investigation', exact: true }).click();
    await expect(page.getByRole('status')).toContainText('Revision 3');
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.locator('.consent-editor').scrollIntoViewIfNeeded();
    await page.screenshot({ path: info.outputPath(`consent-${width}.png`), fullPage: true });
    await page.reload();
    await page.getByRole('button', { name: 'Investigations', exact: true }).click();
    await page.getByRole('button', { name: new RegExp(`Construction access ${width}`) }).click();
    await sections.getByRole('button', { name: 'Requests', exact: true }).click();
    await expect(page.getByLabel('Consent decision')).toHaveValue('granted');
    await expect(page.getByLabel('Consent evidence reference', { exact: true })).toHaveValue(reference);
    const reportPromise = context.waitForEvent('page');
    await page.getByRole('button', { name: 'Report', exact: true }).click();
    const report = await reportPromise;
    await expect(report.locator('body')).toContainText('Landowner contact and consent register');
    await expect(report.locator('body')).toContainText('Example Estates Ltd');
    await expect(report.locator('body')).toContainText(reference);
    await expect(report.locator('body')).toContainText('not a clearance to start work');
    await report.setViewportSize({ width, height: 900 });
    expect(await report.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await report.emulateMedia({ media: 'print' });
    await report.pdf({ path: info.outputPath(`consent-report-${width}.pdf`), format: 'A4' });
    await report.screenshot({ path: info.outputPath(`consent-report-${width}.png`), fullPage: true });
    await report.close();
    expect(failures).toEqual([]);
  });
}