import { expect, test } from '@playwright/test';
import { PNG } from 'pngjs';

for (const width of [1440, 390]) {
  test(`local evidence preview, linking and duplicate confirmation at ${width}`, async ({ page, context }, info) => {
    test.setTimeout(60_000);
    await page.setViewportSize({ width, height: 900 });
    const failures: string[] = [];
    const external: string[] = [];
    page.on('pageerror', error => failures.push(error.message));
    page.on('request', request => { if (/^https?:/.test(request.url()) && !request.url().startsWith('http://127.0.0.1:4318/')) external.push(request.url()); });
    const source = await context.newPage();
    await source.setContent('<h1>Local evidence PDF</h1><p>Page one of the recorded evidence.</p><div style="break-before:page"><h1>Second evidence page</h1><a href="https://example.invalid/">External reference</a></div>');
    const pdf = await source.pdf();
    await source.close();
    await page.goto('/');
    await page.locator('.parcel-row').first().click();
    await page.getByRole('button', { name: 'Start investigation', exact: true }).click();
    await page.getByLabel('Investigation name', { exact: true }).fill(`Evidence viewer ${width}`);
    await page.getByRole('button', { name: 'Save investigation', exact: true }).click();
    await expect(page.getByRole('status')).toContainText('Revision 0');
    const sections = page.getByRole('navigation', { name: 'Case sections' });
    await sections.getByRole('button', { name: 'Documents', exact: true }).click();
    const text = '<script>window.evidenceExecuted=true</script><img src="https://example.invalid/tracker"> Original evidence';
    const textFile = { name: 'evidence.txt', mimeType: 'text/plain', buffer: Buffer.from(text) };
    await page.getByLabel('Evidence document', { exact: true }).setInputFiles(textFile);
    await expect(page.getByRole('status')).toContainText('Revision 1');
    await page.getByRole('button', { name: 'Preview evidence.txt', exact: true }).click();
    const dialog = page.getByRole('dialog', { name: 'Evidence preview' });
    await expect(dialog.locator('.document-text')).toHaveText(text);
    await expect(dialog.locator('script,img')).toHaveCount(0);
    await page.keyboard.press('Escape');
    await expect(dialog).toHaveCount(0);
    page.once('dialog', prompt => prompt.dismiss());
    await page.getByLabel('Evidence document', { exact: true }).setInputFiles(textFile);
    await expect(page.locator('.case-document')).toHaveCount(1);
    page.once('dialog', prompt => prompt.accept());
    await page.getByLabel('Evidence document', { exact: true }).setInputFiles({ ...textFile, name: 'confirmed-copy.txt' });
    await expect(page.getByRole('status')).toContainText('Revision 2');
    await expect(page.locator('.case-document')).toHaveCount(2);
    await page.getByLabel('Evidence document', { exact: true }).setInputFiles({ name: 'plan.pdf', mimeType: 'application/pdf', buffer: pdf });
    await expect(page.getByRole('status')).toContainText('Revision 3');
    await page.getByRole('button', { name: 'Preview plan.pdf', exact: true }).click();
    const canvas = dialog.getByLabel('PDF page 1', { exact: true });
    await expect(canvas).toHaveAttribute('data-ready', 'true');
    const image = PNG.sync.read(await canvas.screenshot());
    let ink = 0;
    for (let offset = 0; offset < image.data.length; offset += 4) if (image.data[offset] < 100) ink++;
    expect(ink).toBeGreaterThan(100);
    await dialog.getByText('Page text', { exact: true }).click();
    await expect(dialog.locator('pre')).toContainText('Local evidence PDF');
    const before = await canvas.evaluate(element => element.getBoundingClientRect().width);
    await dialog.getByRole('button', { name: 'Increase PDF zoom' }).click();
    await expect.poll(() => canvas.evaluate(element => element.getBoundingClientRect().width)).toBeGreaterThan(before);
    await dialog.getByRole('button', { name: 'Next page' }).click();
    await expect(dialog.getByLabel('PDF page 2', { exact: true })).toHaveAttribute('data-ready', 'true');
    await expect(dialog.locator('pre')).toContainText('Second evidence page');
    await dialog.getByRole('button', { name: 'Recognize text locally' }).click();
    await expect(dialog.getByLabel('OCR transcript')).toHaveValue(/Second evidence page/, { timeout: 40_000 });
    await expect(dialog.getByRole('region', { name: 'OCR review' })).toContainText('Page 2');
    await expect(dialog.locator('a[href^="https:"]')).toHaveCount(0);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await dialog.screenshot({ path: info.outputPath(`pdf-preview-${width}.png`) });
    await dialog.getByRole('button', { name: 'Close evidence preview' }).click();
    await sections.getByRole('button', { name: 'Titles', exact: true }).click();
    await page.getByRole('button', { name: 'Add title' }).click();
    await page.getByLabel('Title number', { exact: true }).fill('AV123');
    await page.getByLabel('Title document', { exact: true }).selectOption({ label: 'plan.pdf' });
    await expect(page.getByLabel('Title evidence reference', { exact: true })).toHaveValue(/^doc:/);
    await page.getByRole('button', { name: 'Save investigation', exact: true }).click();
    await expect(page.getByRole('status')).toContainText('Revision 4');
    expect(failures).toEqual([]);
    expect(external).toEqual([]);
  });
}

test('damaged PDF and mismatched evidence hashes fail visibly', async ({ page }) => {
  await page.goto('/');
  await page.locator('.parcel-row').first().click();
  await page.getByRole('button', { name: 'Start investigation', exact: true }).click();
  await page.getByRole('button', { name: 'Save investigation', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Revision 0');
  await page.getByRole('navigation', { name: 'Case sections' }).getByRole('button', { name: 'Documents', exact: true }).click();
  await page.getByLabel('Evidence document', { exact: true }).setInputFiles({ name: 'damaged.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.7 invalid') });
  await expect(page.getByRole('status')).toContainText('Revision 1');
  await page.getByRole('button', { name: 'Preview damaged.pdf' }).click();
  const dialog = page.getByRole('dialog', { name: 'Evidence preview' });
  await expect(dialog.getByRole('alert')).toContainText('PDF preview unavailable');
  await dialog.getByRole('button', { name: 'Close evidence preview' }).click();
  await page.route('**/documents/*', route => route.fulfill({ status: 200, contentType: 'application/pdf', body: '%PDF-1.7 changed' }));
  await page.getByRole('button', { name: 'Preview damaged.pdf' }).click();
  await expect(dialog.getByRole('alert')).toContainText('integrity check failed');
});

test('image preview renders locally and rejects oversized dimensions before decoding', async ({ page }, info) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await page.locator('.parcel-row').first().click();
  await page.getByRole('button', { name: 'Start investigation', exact: true }).click();
  await page.getByRole('button', { name: 'Save investigation', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Revision 0');
  await page.getByRole('navigation', { name: 'Case sections' }).getByRole('button', { name: 'Documents', exact: true }).click();
  const image = new PNG({ width: 120, height: 90 });
  for (let offset = 0; offset < image.data.length; offset += 4) {
    image.data[offset] = 32; image.data[offset + 1] = 130; image.data[offset + 2] = 98; image.data[offset + 3] = 255;
  }
  const buffer = PNG.sync.write(image);
  await page.getByLabel('Evidence document', { exact: true }).setInputFiles({ name: 'site.png', mimeType: 'image/png', buffer });
  await expect(page.getByRole('status')).toContainText('Revision 1');
  await page.getByRole('button', { name: 'Preview site.png' }).click();
  const dialog = page.getByRole('dialog', { name: 'Evidence preview' });
  await expect(dialog.getByRole('img')).toBeVisible();
  await expect.poll(() => dialog.getByRole('img').evaluate(element => (element as HTMLImageElement).naturalWidth)).toBe(120);
  await dialog.screenshot({ path: info.outputPath('image-preview-390.png') });
  await dialog.getByRole('button', { name: 'Close evidence preview' }).click();
  buffer.writeUInt32BE(100_000, 16);
  await page.getByLabel('Evidence document', { exact: true }).setInputFiles({ name: 'oversized.png', mimeType: 'image/png', buffer });
  await expect(page.getByRole('status')).toContainText('Revision 2');
  await page.getByRole('button', { name: 'Preview oversized.png' }).click();
  await expect(dialog.getByRole('alert')).toContainText('exceeds the preview size limit');
  await expect(dialog.getByRole('img')).toHaveCount(0);
});