import { expect, test } from '@playwright/test';

for (const width of [1440, 390]) {
  test(`readiness gaps focus the correct record at ${width}`, async ({ page }, info) => {
    test.setTimeout(90_000);
    await page.setViewportSize({ width, height: 900 });
    await page.goto('/');
    await page.locator('.parcel-row').first().click();
    await page.getByRole('button', { name: 'Start investigation', exact: true }).click();
    const readiness = page.getByRole('region', { name: 'Evidence readiness' });
    await readiness.locator('summary').click();
    const follow = async (name: string) => {
      const link = readiness.getByRole('button', { name, exact: true });
      await link.focus();
      await page.keyboard.press('Enter');
    };
    await expect(readiness).toContainText('Checks cover recorded information only');
    await follow('Project: Project name is not recorded.');
    await expect(page.getByLabel('Project name', { exact: true })).toBeFocused();
    await follow('Requests: No consent requests are recorded.');
    await expect(page.getByRole('button', { name: 'Add consent request', exact: true })).toBeDisabled();
    await expect(page.locator('.case-fields')).toBeFocused();
    await follow('Titles: No title evidence is recorded.');
    await expect(page.getByRole('button', { name: 'Add title', exact: true })).toBeFocused();
    await page.keyboard.press('Enter');
    await page.getByLabel('Title number', { exact: true }).fill('AV12345');
    await page.getByRole('button', { name: 'Add title', exact: true }).click();
    await page.getByLabel('Title number', { exact: true }).nth(1).fill('AV12346');
    await follow('Title 2: AV12346: Title evidence reference is not recorded.');
    await expect(page.getByLabel('Title evidence reference', { exact: true }).nth(1)).toBeFocused();
    await page.keyboard.type('Second title evidence');
    await expect(page.getByLabel('Title evidence reference', { exact: true }).first()).toHaveValue('');
    await expect(readiness.getByRole('button', { name: 'Title 2: AV12346: Title evidence reference is not recorded.', exact: true })).toHaveCount(0);
    await follow('Title 2: AV12346: Parcel relationship is unconfirmed.');
    await expect(page.getByLabel('Parcel relationship').nth(1)).toBeFocused();
    await follow('Parties: No relevant parties are recorded.');
    await expect(page.getByRole('button', { name: 'Add party', exact: true })).toBeFocused();
    await page.keyboard.press('Enter');
    await page.getByLabel('Party name', { exact: true }).fill('Example Estates');
    await page.getByRole('button', { name: 'Add party', exact: true }).click();
    await page.getByLabel('Party name', { exact: true }).nth(1).fill('Example Estates');
    await follow('Party 2: Example Estates: Authority evidence reference is not recorded.');
    await expect(page.getByLabel('Authority evidence reference', { exact: true }).nth(1)).toBeFocused();
    await follow('Party 1: Example Estates: Authority reviewer is not recorded.');
    await expect(page.getByLabel('Authority checked by', { exact: true }).first()).toBeFocused();
    await follow('Requests: No consent requests are recorded.');
    await expect(page.getByRole('button', { name: 'Add consent request', exact: true })).toBeFocused();
    await page.keyboard.press('Enter');
    await page.getByRole('button', { name: 'Add consent request', exact: true }).click();
    await follow('Request 2: Example Estates: Proposed activities are not recorded.');
    await expect(page.getByLabel('Proposed activities', { exact: true }).nth(1)).toBeFocused();
    await follow('Request 1: Example Estates: Consent request is not recorded as sent.');
    await expect(page.getByLabel('Consent decision', { exact: true }).first()).toBeFocused();
    await expect(page.getByLabel('Consent decision', { exact: true }).first()).toHaveValue('not requested');
    await follow('Correspondence: No correspondence is recorded.');
    await expect(page.getByRole('button', { name: 'Add correspondence', exact: true })).toBeFocused();
    await page.keyboard.press('Enter');
    await page.getByRole('button', { name: 'Add correspondence', exact: true }).click();
    await follow('Correspondence 2: Example Estates: Correspondence date is not recorded.');
    await expect(page.getByLabel('Correspondence date', { exact: true }).nth(1)).toBeFocused();
    await follow('Correspondence 1: Example Estates: Correspondence summary is not recorded.');
    await expect(page.getByLabel('Correspondence summary', { exact: true }).first()).toBeFocused();
    await follow('Title 1: AV12345: Title evidence reference is not recorded.');
    await page.getByLabel('Title evidence reference', { exact: true }).first().fill('doc:00000000-0000-4000-8000-000000000001');
    await follow('Documents: Referenced document doc:00000000-0000-4000-8000-000000000001 is not attached.');
    await expect(page.locator('.case-fields')).toBeFocused();
    await expect(page.getByLabel('Evidence document', { exact: true })).toBeDisabled();
    await expect(page.locator('.case-fields')).toContainText('Save case changes before attaching files.');
    await readiness.scrollIntoViewIfNeeded();
    await expect(page.locator('body')).toHaveJSProperty('scrollWidth', width);
    await page.screenshot({ path: info.outputPath('readiness-gaps.png'), fullPage: true });
  });
}