import type { Investigation } from '../../../packages/contracts/src/investigation.ts';
import { effectiveConsentStatus } from '../../../packages/contracts/src/consent.ts';
import { evaluateEvidenceReadiness } from '../../../packages/contracts/src/readiness.ts';

export function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]!);
}
const paragraph = (label: string, value: string) => `<p><strong>${escapeHtml(label)}:</strong> ${escapeHtml(value || 'Not recorded')}</p>`;

export function consentReport(item: Investigation): string {
  const lifecycle = item.workflow?.lifecycle;
  const records = lifecycle ? `<section class="notes-section"><h2>Records lifecycle</h2>${paragraph('Record state', lifecycle.state)}${paragraph('Legal hold', lifecycle.legalHold ? 'Active' : 'Not active')}${paragraph('Hold reason', lifecycle.holdReason)}${paragraph('Hold release reason', lifecycle.releaseReason)}${paragraph('Reviewed by / on', `${lifecycle.reviewedBy} / ${lifecycle.reviewedOn}`)}${paragraph('Decision reason', lifecycle.decisionReason)}<p>Reviewer identity is a recorded assertion, not authenticated identity. No records have been erased by this decision.</p></section>` : '';
  return records + consentRegisterReport(item);
}

function consentRegisterReport(item: Investigation): string {
  const workflow = item.workflow;
  if (!workflow) return '';
  const parcelIds = (item.snapshot.parcels ?? [item.snapshot.parcel]).map(parcel => parcel.id);
  const readiness = evaluateEvidenceReadiness(workflow, item.documents, undefined, parcelIds);
  const scope = (ids?: string[]) => (ids ?? (parcelIds.length === 1 ? parcelIds : [])).join(', ');
  const readinessRequests = readiness.requests.map(request => `<li>${escapeHtml(request.partyName)}: ${escapeHtml(request.state)}${request.validFrom || request.validUntil ? ` (${escapeHtml(request.validFrom || 'no start date')} to ${escapeHtml(request.validUntil || 'no end date')})` : ''}</li>`).join('');
  const readinessGaps = readiness.gaps.map(gap => `<li>${escapeHtml(gap.section)}: ${escapeHtml(gap.message)}</li>`).join('');
  const titles = workflow.titles.map(title => `<article><h3>${escapeHtml(title.titleNumber)} / ${escapeHtml(title.tenure)}</h3>${paragraph('Parcel scope', scope(title.parcelIds))}${paragraph('Case assessment', title.verification)}${paragraph('Relationship to parcel', title.relationship)}${paragraph('Extent assessment', title.extentNotes)}${paragraph('Evidence', title.evidenceRef)}${paragraph('Source date', title.evidenceDate)}${paragraph('Checked by / on', `${title.reviewedBy} / ${title.reviewedOn}`)}</article>`).join('');
  const parties = workflow.parties.map(party => `<article><h3>${escapeHtml(party.name)}</h3>${paragraph('Capacity', party.capacity)}${paragraph('Title', workflow.titles.find(title => title.id === party.titleId)?.titleNumber ?? '')}${paragraph('Postal address', party.postalAddress)}${paragraph('Email', party.email)}${paragraph('Phone', party.phone)}${paragraph('Contact source', party.contactSource)}${paragraph('Contact check', `${party.contactUse} / ${party.contactCheckedOn}`)}${paragraph('Authority evidence', party.authorityEvidence)}${paragraph('Authority checked by / on', `${party.authorityCheckedBy} / ${party.authorityCheckedOn}`)}</article>`).join('');
  const consents = workflow.consents.map(permission => `<article><h3>${escapeHtml(workflow.parties.find(party => party.id === permission.partyId)?.name ?? 'Missing party')} / ${escapeHtml(effectiveConsentStatus(permission))}</h3>${paragraph('Parcel scope', scope(permission.parcelIds))}${paragraph('Recorded decision', permission.status)}${paragraph('Activities', permission.activities)}${paragraph('Land scope', permission.landScope)}${paragraph('Request / response dates', `${permission.requestedOn} / ${permission.responseOn}`)}${paragraph('Valid from / until', `${permission.validFrom} / ${permission.validUntil}`)}${paragraph('Conditions', permission.conditions)}${paragraph('Signatory', permission.signatory)}${paragraph('Decision evidence', permission.evidenceRef)}</article>`).join('');
  const correspondence = workflow.correspondence.map(entry => `<article><h3>${escapeHtml(entry.date)} / ${escapeHtml(entry.direction)} / ${escapeHtml(entry.method)}</h3>${paragraph('Party', workflow.parties.find(party => party.id === entry.partyId)?.name ?? '')}${paragraph('Summary', entry.summary)}${paragraph('Evidence', entry.evidenceRef)}</article>`).join('');
  return `<section class="notes-section"><h2>Landowner contact and consent register</h2>${paragraph('Project', workflow.project)}${paragraph('Requesting company / contact', workflow.requester)}${paragraph('Reply address', workflow.replyAddress)}${paragraph('Retention review', workflow.retentionReviewOn)}<p>Case assessments are entered by your team, not independently verified by this application. Recorded consent is limited to its parties, activities, land, dates and conditions. Other rights-holder approvals may be required. This report is not a clearance to start work.</p><h2>Evidence readiness</h2>${paragraph('Evaluated on', readiness.evaluatedOn)}${paragraph('Retention review state', `${readiness.retention.state}${readiness.retention.reviewOn ? ` / ${readiness.retention.reviewOn}` : ''}`)}<p>${readiness.counts.unresolvedGaps} factual record gaps identified. This is not a legal or works approval.</p>${readinessRequests ? `<h3>Request states</h3><ul>${readinessRequests}</ul>` : '<p>No consent requests recorded.</p>'}${readinessGaps ? `<h3>Record gaps</h3><ul>${readinessGaps}</ul>` : '<p>No factual record gaps identified.</p>'}<h2>Title evidence</h2>${titles || '<p>No title evidence recorded.</p>'}<h2>Relevant parties</h2>${parties || '<p>No parties identified.</p>'}<h2>Consent decisions</h2>${consents || '<p>No consent recorded.</p>'}<h2>Correspondence</h2>${correspondence || '<p>No correspondence recorded.</p>'}<h2>Evidence documents</h2>${item.documents.map(document => paragraph(document.name, `doc:${document.id} | SHA-256 ${document.sha256} | ${document.uploadedAt}`)).join('') || '<p>No files attached.</p>'}<p>Confidential project record. Contains contact details and correspondence; share only with authorised recipients.</p></section>`;
}

export function consentRequest(item: Investigation, permissionId: string, nonce: string): string {
  const workflow = item.workflow;
  const permission = workflow.consents.find(candidate => candidate.id === permissionId);
  const party = workflow.parties.find(candidate => candidate.id === permission?.partyId);
  if (!permission || !party) throw new Error('Consent record not found');
  const parcelIds = (item.snapshot.parcels ?? [item.snapshot.parcel]).map(parcel => parcel.id);
  const requestParcelIds = permission.parcelIds ?? (parcelIds.length === 1 ? parcelIds : []);
  if (!requestParcelIds.length || requestParcelIds.some(id => !parcelIds.includes(id))) throw new Error('Request needs explicit parcel scope within the case');
  if (party.contactUse !== 'approved' || !(party.email || party.postalAddress) || !workflow.project.trim() || !workflow.requester.trim() || !workflow.replyAddress.trim() || !permission.activities.trim() || !permission.landScope.trim() || !permission.validFrom || !permission.validUntil) throw new Error('Request needs approved postal/email contact, project, requester, reply address, activities, land scope and proposed dates');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Consent request draft</title><style>body{font:16px Georgia,serif;line-height:1.6;margin:0;color:#213b30;overflow-wrap:anywhere}main{max-width:760px;margin:auto;padding:28px}h1{font-size:26px}p{white-space:pre-wrap}button{padding:10px;font:inherit}@media print{button{display:none}@page{margin:20mm}main{padding:0}}</style></head><body><main><button id="print">Print / Save as PDF</button><h1>Request for land access / works consent</h1><p>DRAFT / NOT SENT / saved case revision ${item.revision}</p>${paragraph('To', party.name)}${paragraph('Address / email', [party.postalAddress, party.email].filter(Boolean).join('\n'))}${paragraph('From', workflow.requester)}${paragraph('Project', workflow.project)}${paragraph('Reply to', workflow.replyAddress)}<p>We request your written agreement for the following proposed activities. Please confirm your interest in the land and your authority to grant the requested permission, or identify the appropriate authorised contact.</p>${paragraph('Proposed activities', permission.activities)}${paragraph('Land and plan reference', permission.landScope)}${paragraph('Proposed dates', `${permission.validFrom} to ${permission.validUntil}`)}${paragraph('Proposed conditions / restrictions', permission.conditions)}${paragraph('Parcel reference', requestParcelIds.join(', '))}<p>The INSPIRE outline is indicative only and is not a legal boundary. Please refer to the agreed scope plan and supporting documents, which must accompany this request where relevant.</p><p>Please provide your decision in writing, identifying the permitted activities, land, dates, conditions and the signatory's capacity and authority. Silence will not be treated as consent. No permission is created by this draft, and other necessary approvals remain separate.</p>${paragraph('Case reference', item.id)}</main><script nonce="${escapeHtml(nonce)}">document.getElementById('print').addEventListener('click',()=>window.print());</script></body></html>`;
}